-- Core Contracts Registry v1: PostgreSQL is the canonical configuration store.
-- The migration is idempotent and is applied by the registry bootstrap.

CREATE TABLE IF NOT EXISTS core_contracts_registry_revision (
    id UUID PRIMARY KEY,
    revision BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile TEXT NOT NULL CHECK (profile IN ('benni', 'eltern')),
    schema_version INTEGER NOT NULL CHECK (schema_version > 0),
    payload JSONB NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('draft', 'active', 'superseded', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ,
    checksum TEXT NOT NULL CHECK (checksum ~ '^[0-9a-f]{64}$'),
    created_by TEXT,
    CHECK (
        (status IN ('active', 'superseded') AND activated_at IS NOT NULL)
        OR (status IN ('draft', 'rejected') AND activated_at IS NULL)
    ),
    UNIQUE (profile, revision)
);

CREATE UNIQUE INDEX IF NOT EXISTS core_contracts_registry_revision_one_active_per_profile
    ON core_contracts_registry_revision (profile)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS core_contracts_registry_revision_profile_revision_idx
    ON core_contracts_registry_revision (profile, revision DESC);
